In [1]:
import numpy as np
from scipy import sparse

# Vectors

In [2]:
vector_row=np.array([1,2,3])

In [3]:
vector_columns=np.array([[1],[2],[3]])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
vector_columns

array([[1],
       [2],
       [3]])

In [6]:
list1 = [1, 2, 3]

In [7]:
vector = np.array(list1)

In [8]:
scalar = 2

In [9]:
scalar_mul = vector * scalar

# Matrices

In [10]:
matrix=np.mat([[1,2],[2,4],[4,6]])

In [11]:
matrix

matrix([[1, 2],
        [2, 4],
        [4, 6]])

In [12]:
#Sparse Matrix
matrix=np.array([[0,1],
               [0,0],
                [3,0]])

In [13]:
matrix_sparse=sparse.csr_matrix(matrix)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

# Practice

In [14]:
vector=np.array([0,1, 2,3, 5,6, 7,8,9,10])

In [15]:
vector[:]

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10])

In [16]:
vector[:4]

array([0, 1, 2, 3])

In [17]:
vector[-3:]

array([ 8,  9, 10])

In [18]:
matrix = np.array([[61, 92, 83],
                   [74, 15, 6],
                   [667, 8, 279],
                  [224,0,876]])

In [19]:
matrix[:3,2:]

array([[ 83],
       [  6],
       [279]])

In [20]:
matrix[-1:,:]

array([[224,   0, 876]])

In [21]:
matrix[1,2]

6

In [22]:
matrix[:,1:-1]

array([[92],
       [15],
       [ 8],
       [ 0]])

In [23]:
# Maximum element in matrix
np.max(matrix)

876

In [24]:
# maximum element in each row in a matrix
np.max(matrix,axis=0)

array([667,  92, 876])

In [25]:
# minimum element in each row in a matrix
np.min(matrix,axis=0)

array([61,  0,  6])

# Average, Variance and Standard Variance

In [26]:
np.mean(matrix)

198.75

In [27]:
np.var(matrix)

74261.52083333333

In [28]:
np.std(matrix)

272.50967108220823

# Reshaping Arrays

In [29]:
matrix.reshape(4,3)

array([[ 61,  92,  83],
       [ 74,  15,   6],
       [667,   8, 279],
       [224,   0, 876]])

In [30]:
matrix.reshape(2,6)

array([[ 61,  92,  83,  74,  15,   6],
       [667,   8, 279, 224,   0, 876]])

In [31]:
matrix.reshape(6,2)

array([[ 61,  92],
       [ 83,  74],
       [ 15,   6],
       [667,   8],
       [279, 224],
       [  0, 876]])

In [33]:
matrix.flatten()

array([ 61,  92,  83,  74,  15,   6, 667,   8, 279, 224,   0, 876])

In [34]:
matrix.diagonal()

array([ 61,  15, 279])

In [35]:
matrix.trace()

355